In [50]:
import pandas as pd
import numpy as np
from numpy import count_nonzero

df = pd.read_csv('Global_Baseline.csv')
df

Critic  Give Me Five  MOON MAN  Warrious of Future  Minions  Return to Dust
0     Ao           3.0       3.0                 1.0      5.0             5.0
1    Han           3.0       4.0                 NaN      5.0             3.0
2     Yu           2.0       4.0                 3.0      NaN             4.0
3     Bo           1.0       NaN                 3.0      3.0             NaN
4   Miao           4.0       2.0                 NaN      3.0             5.0
5     Ye           2.0       NaN                 3.0      5.0             NaN
6    Fei           NaN       2.0                 2.0      4.0             4.0

In [51]:
df_index = ['Give Me Five','MOON MAN','Warrious of Future','Minions','Return to Dust']

In [52]:
df.fillna(0, inplace=True)
df.drop('Critic',axis = 1, inplace = True)
df = df.T
df_1 = df.values
df_1

array([[3., 3., 2., 1., 4., 2., 0.],
       [3., 4., 4., 0., 2., 0., 2.],
       [1., 0., 3., 3., 0., 3., 2.],
       [5., 5., 0., 3., 3., 5., 4.],
       [5., 3., 4., 0., 5., 0., 4.]])

In [53]:
df

0    1    2    3    4    5    6
Give Me Five        3.0  3.0  2.0  1.0  4.0  2.0  0.0
MOON MAN            3.0  4.0  4.0  0.0  2.0  0.0  2.0
Warrious of Future  1.0  0.0  3.0  3.0  0.0  3.0  2.0
Minions             5.0  5.0  0.0  3.0  3.0  5.0  4.0
Return to Dust      5.0  3.0  4.0  0.0  5.0  0.0  4.0

In [33]:
from sklearn.neighbors import NearestNeighbors

In [34]:
knn = NearestNeighbors(metric='cosine', algorithm='brute')
knn.fit(df_1)
distances, indices = knn.kneighbors(df_1, n_neighbors=3)

In [35]:
indices

array([[0, 3, 4],
       [1, 4, 2],
       [2, 1, 4],
       [3, 0, 2],
       [4, 1, 0]], dtype=int64)

In [36]:
distances

array([[0.        , 0.2487292 , 0.38108813],
       [0.        , 0.0580406 , 0.31034369],
       [0.        , 0.31034369, 0.42433588],
       [0.        , 0.2487292 , 0.68148897],
       [0.        , 0.0580406 , 0.38108813]])

### Example: Predict the rating for Minions by Yu 

In [61]:
index_for_movie = df.index.tolist().index('Minions') # it returns 0
sim_movies = indices[index_for_movie].tolist() # make list for similar movies
movie_distances = distances[index_for_movie].tolist() # the list for distances of similar movies
id_movie = sim_movies.index(index_for_movie) # get the position of the movie itself in indices and distances
sim_movies.remove(index_for_movie) # remove the movie itself in indices
movie_distances.pop(id_movie) # remove the movie itself in distances

print('The Nearest Movies to Minions:', sim_movies)
print('The Distance from Minions:', movie_distances)

The Nearest Movies to Minions: [0, 2]
The Distance from Minions: [0.2487292003492918, 0.6814889713646969]


In [62]:
movie_similarity = [-x+1 for x in movie_distances] # inverse distance 

predicted_rating = (movie_similarity[0]*df.iloc[sim_movies[0],2] + movie_similarity[1]*df.iloc[sim_movies[1],2])/sum(movie_similarity)
print(predicted_rating)

2.2977345662578856


### The predict score is 2.2977

In [66]:
pip install lightfm

Note: you may need to restart the kernel to use updated packages.


In [73]:
from lightfm import LightFM
from scipy.sparse import csr_matrix

In [78]:
data = csr_matrix(df)
data

<5x7 sparse matrix of type '<class 'numpy.float64'>'
	with 27 stored elements in Compressed Sparse Row format>

In [75]:
model = LightFM()

In [77]:
model.fit(data)

In [81]:
model.get_user_representations()

model.get_item_representations()

model.predict_rank(data)


<5x7 sparse matrix of type '<class 'numpy.float32'>'
	with 27 stored elements in Compressed Sparse Row format>