### 1. Ass1 Table

In [11]:
import pandas as pd
import numpy as np
from numpy import count_nonzero

df = pd.read_csv('Global_Baseline.csv')
df

Critic  Give Me Five  MOON MAN  Warrious of Future  Minions  Return to Dust
0     Ao           3.0       3.0                 1.0      5.0             5.0
1    Han           3.0       NaN                 NaN      5.0             NaN
2     Yu           NaN       4.0                 3.0      NaN             4.0
3     Bo           1.0       NaN                 3.0      3.0             NaN
4   Miao           4.0       2.0                 NaN      NaN             5.0
5     Ye           2.0       NaN                 NaN      5.0             NaN
6    Fei           NaN       2.0                 2.0      NaN             4.0

In [12]:
df = df.drop(columns = ['Critic'])
df

Give Me Five  MOON MAN  Warrious of Future  Minions  Return to Dust
0           3.0       3.0                 1.0      5.0             5.0
1           3.0       NaN                 NaN      5.0             NaN
2           NaN       4.0                 3.0      NaN             4.0
3           1.0       NaN                 3.0      3.0             NaN
4           4.0       2.0                 NaN      NaN             5.0
5           2.0       NaN                 NaN      5.0             NaN
6           NaN       2.0                 2.0      NaN             4.0

In [15]:
A = np.array(df)

#If you have Nan
A = np.nan_to_num(A,0)

print(A)


# calculate sparsity
sparsity = 1.0 - ( count_nonzero(A) / float(A.size) )
print(sparsity)

[[3. 3. 1. 5. 5.]
 [3. 0. 0. 5. 0.]
 [0. 4. 3. 0. 4.]
 [1. 0. 3. 3. 0.]
 [4. 2. 0. 0. 5.]
 [2. 0. 0. 5. 0.]
 [0. 2. 2. 0. 4.]]
0.4


### 2. jester-data-1 :  Missing Data

In [17]:
df = pd.read_csv('jester-data-1.csv',header = None)
df

0      1      2      3      4     5      6     7     8      9    ...  \
0       74  -7.82   8.79  -9.66  -8.16 -7.52  -8.50 -9.85  4.17  -8.98  ...   
1      100   4.08  -0.29   6.36   4.37 -2.38  -9.66 -0.73 -5.34   8.88  ...   
2       49  99.00  99.00  99.00  99.00  9.03   9.27  9.03  9.27  99.00  ...   
3       48  99.00   8.35  99.00  99.00  1.80   8.16 -2.82  6.21  99.00  ...   
4       91   8.50   4.61  -4.17  -5.39  1.36   1.60  7.04  4.61  -0.44  ...   
...    ...    ...    ...    ...    ...   ...    ...   ...   ...    ...  ...   
24978  100   0.44   7.43   9.08   2.33  3.20   6.75 -8.79 -0.53  -8.74  ...   
24979   91   9.13  -8.16   8.59   9.08  0.87  -8.93 -3.50  5.78  -8.11  ...   
24980   39  99.00  99.00  99.00  99.00 -7.77  99.00  6.70 -6.75  99.00  ...   
24981   37  99.00  99.00  99.00  99.00 -9.71  99.00  4.56 -8.30  99.00  ...   
24982   72   2.43   2.67  -3.98   4.27 -2.28   7.33  2.33  4.56   6.75  ...   

         91     92     93     94     95     96     97     98     99     100  
0       2.82  99.00  99.00  99.00  99.00  99.00  -5.63  99.00  99.00  99.00  
1       2.82  -4.95  -0.29   7.86  -0.19  -2.14   3.06   0.34  -4.32   1.07  
2      99.00  99.00  99.00   9.08  99.00  99.00  99.00  99.00  99.00  99.00  
3      99.00  99.00  99.00   0.53  99.00  99.00  99.00  99.00  99.00  99.00  
4       5.19   5.58   4.27   5.19   5.73   1.55   3.11   6.55   1.80   1.60  
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
24978   8.83  -1.21   9.22  -6.70   8.45   9.03   6.55   8.69   8.79   7.43  
24979  -1.17  -5.73  -1.46   0.24   9.22  -8.20  -7.23  -8.59   9.13   8.45  
24980  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  
24981  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  
24982  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  

[24983 rows x 101 columns]

In [20]:
# replace 99 to 0
df.replace({99:0},inplace=True)
A = np.array(df)

#If you have Nan
A = np.nan_to_num(A,0)
print(A)


# calculate sparsity
sparsity = 1.0 - ( count_nonzero(A) / float(A.size) )
print(sparsity)

[[ 74.    -7.82   8.79 ...   0.     0.     0.  ]
 [100.     4.08  -0.29 ...   0.34  -4.32   1.07]
 [ 49.     0.     0.   ...   0.     0.     0.  ]
 ...
 [ 39.     0.     0.   ...   0.     0.     0.  ]
 [ 37.     0.     0.   ...   0.     0.     0.  ]
 [ 72.     2.43   2.67 ...   0.     0.     0.  ]]
0.27476466175216974


### 3. Movie Table: Long to Wide

In [26]:
df = pd.read_csv('ratings.csv')
df

userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [28]:
df = df.drop(columns = ['timestamp'])
df

userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100831     610   166534     4.0
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0

[100836 rows x 3 columns]

In [30]:
df = df.pivot(index = "userId",columns = "movieId",values = "rating")
df

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     NaN     4.0     NaN     NaN     4.0     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...     ...     ...     ...     ...     ...     ...   
606         2.5     NaN     NaN     NaN     NaN     NaN     2.5     NaN   
607         4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
608         2.5     2.0     2.0     NaN     NaN     NaN     NaN     NaN   
609         3.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
610         5.0     NaN     NaN     NaN     NaN     5.0     NaN     NaN   

movieId  9       10      ...  193565  193567  193571  193573  193579  193581  \
userId                   ...                                                   
1           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...  ...     ...     ...     ...     ...     ...     ...   
606         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
607         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
608         NaN     4.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   
609         NaN     4.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   
610         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  193583  193585  193587  193609  
userId                                   
1           NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN  
...         ...     ...     ...     ...  
606         NaN     NaN     NaN     NaN  
607         NaN     NaN     NaN     NaN  
608         NaN     NaN     NaN     NaN  
609         NaN     NaN     NaN     NaN  
610         NaN     NaN     NaN     NaN  

[610 rows x 9724 columns]

In [31]:
A = np.array(df)

#If you have Nan
A = np.nan_to_num(A,0)
print(A)


# calculate sparsity
sparsity = 1.0 - ( count_nonzero(A) / float(A.size) )
print(sparsity)

[[4.  0.  4.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 ...
 [2.5 2.  2.  ... 0.  0.  0. ]
 [3.  0.  0.  ... 0.  0.  0. ]
 [5.  0.  0.  ... 0.  0.  0. ]]
0.9830003169443864
